#!/bin/sh
# Xcode Cloud runs this after cloning, before resolving packages or building.
#
# WHY: PiDashboard.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored (ios/.gitignore:12), so it does not exist in a fresh clone. Local
# builds work because the file is already on disk. Cloud builds 1-4 failed with
# "Project PiDashboard.xcodeproj does not exist at ios/PiDashboard/PiDashboard.xcodeproj".
#
# Xcode Cloud looks for ci_scripts NEXT TO the Xcode project, not only at the
# repository root; a root-only copy was not executed (build 4 finished in 20s,
# far too fast for the brew install below to have run).

set -e
echo "--- ci_post_clone: generating Xcode project from project.yml ---"

cd "$CI_PRIMARY_REPOSITORY_PATH/ios/PiDashboard"
echo "working dir: $(pwd)"

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "installing xcodegen…"
  brew install xcodegen
fi

xcodegen generate

if [ ! -d "PiDashboard.xcodeproj" ]; then
  echo "ERROR: xcodegen ran but PiDashboard.xcodeproj was not produced" >&2
  exit 1
fi

echo "--- ci_post_clone: project generated ---"
ls -d PiDashboard.xcodeproj
